### ISSUE TITLE
如何启动

### ISSUE THREAD

**Issue by liuqiaoLQ** [xiaohuiduan/pbft#1]
您好，我想问问您怎么运行这个工程来查看是否成功实现了PBFT共识过程啊？

**Comment by xiaohuiduan** [comment]
在代码里面节点在PBFT的过程中会使用日志来打印共识的过程

**Comment by liuqiaoLQ** [comment]
我没表达清楚，我想问多个main函数情况下如何启动多个共识节点和客户端呢？

**Comment by xiaohuiduan** [comment]
> 我没表达清楚，我想问多个main函数情况下如何启动多个共识节点和客户端呢？

每次启动一个main程序，实际上就是启动了一个节点

**Comment by liuqiaoLQ** [comment]
谢谢，我还想问那主节点一直都是index=0的节点吗，还有怎么停止发送预准备消息呢，我输入预准备消息体，怎么看到共识过程？

**Comment by xiaohuiduan** [comment]
> 谢谢，我还想问那主节点一直都是index=0的节点吗，还有怎么停止发送预准备消息呢，我输入预准备消息体，怎么看到共识过程？

主节点默认是index=0的节点，主节点是可以change的，但是我没有写这个功能。
在Main.java文件中，有一个被注释的代码：
![code](https://user-images.githubusercontent.com/40485068/86078113-f16a0b00-babf-11ea-8c91-f3b2da39e0a5.png)
这个地方可以输入交易的信息。当消息输入完成时，就会进入共识过程。共识过程我是使用log去打印的。

**Comment by xiaohuiduan** [comment]
> > 谢谢，我还想问那主节点一直都是index=0的节点吗，还有怎么停止发送预准备消息呢，我输入预准备消息体，怎么看到共识过程？
> 
> 主节点默认是index=0的节点，主节点是可以change的，但是我没有写这个功能。
> 在Main.java文件中，有一个被注释的代码：
> ![code](https://user-images.githubusercontent.com/40485068/86078113-f16a0b00-babf-11ea-8c91-f3b2da39e0a5.png)
> 这个地方可以输入交易的信息。当消息输入完成时，就会进入共识过程。共识过程我是使用log去打印的。

当然，我也是新手，不确定这种方式正不正确。😄

**Comment by liuqiaoLQ** [comment]
怎么样完成交易信息输入呢，有什么特殊格式吗，我输入一个字符串后换行还是让我继续输入




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaohuiduan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 上午10:55
收件人:&nbsp;"xiaohuiduan/pbft"<pbft@noreply.github.com&gt;;
抄送:&nbsp;"逆光🌻"<1429682784@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohuiduan/pbft] 如何启动 (#1)





  
谢谢，我还想问那主节点一直都是index=0的节点吗，还有怎么停止发送预准备消息呢，我输入预准备消息体，怎么看到共识过程？
  
主节点默认是index=0的节点，主节点是可以change的，但是我没有写这个功能。
 在Main.java文件中，有一个被注释的代码：
 
 这个地方可以输入交易的信息。当消息输入完成时，就会进入共识过程。共识过程我是使用log去打印的。
