### ISSUE TITLE
怎么样完成交易信息输入呢，有什么特殊格式吗

### ISSUE THREAD

**Issue by xiaohuiduan** [xiaohuiduan/pbft#2]
怎么样完成交易信息输入呢，有什么特殊格式吗，我输入一个字符串后换行还是让我继续输入

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaohuiduan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 上午10:55
收件人:&nbsp;"xiaohuiduan/pbft"<pbft@noreply.github.com&gt;;
抄送:&nbsp;"逆光🌻"<1429682784@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohuiduan/pbft] 如何启动 (#1)

  
谢谢，我还想问那主节点一直都是index=0的节点吗，还有怎么停止发送预准备消息呢，我输入预准备消息体，怎么看到共识过程？
  
主节点默认是index=0的节点，主节点是可以change的，但是我没有写这个功能。
 在Main.java文件中，有一个被注释的代码：
 
 这个地方可以输入交易的信息。当消息输入完成时，就会进入共识过程。共识过程我是使用log去打印的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

_Originally posted by @liuqiaoLQ in https://github.com/xiaohuiduan/pbft/issues/1#issuecomment-651493965_

**Comment by xiaohuiduan** [comment]
没有特殊格式，我是写了一个while(True)的死循环，所以会一直要求你输入交易信息，输入交易信息回车即可，就代表向网络中发送一条交易信息

![image](https://user-images.githubusercontent.com/40485068/86078493-da77e880-bac0-11ea-83f3-4547547337ac.png)

**Comment by liuqiaoLQ** [comment]
哦哦，好的，谢谢你啦


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xiaohuiduan"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月30日(星期二) 中午11:02
收件人:&nbsp;"xiaohuiduan/pbft"<pbft@noreply.github.com&gt;;
抄送:&nbsp;"逆光?"<1429682784@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [xiaohuiduan/pbft] 怎么样完成交易信息输入呢，有什么特殊格式吗 (#2)





 
没有特殊格式，我是写了一个while(True)的死循环，所以会一直要求你输入交易信息，输入交易信息回车即可，就代表向网络中发送一条交易信息
