### ISSUE TITLE
大佬写的不错啊！

### ISSUE THREAD

**Issue by parkt90** [xiaohuiduan/pbft#5]
求大佬继续更新一波啊，比如拜占庭节点处理数据和超时机制。

**Comment by xiaohuiduan** [comment]
> 求大佬继续更新一波啊，比如拜占庭节点处理数据和超时机制。

我应该不会更新了，现在读研的方向不是这个了。你可以尝试自己去实现这两个方法，嘿嘿嘿

**Comment by parkt90** [comment]
好的，在下只能板门弄斧了。

**Comment by xiaohuiduan** [comment]
> 好的，在下只能板门弄斧了。

hhh，其实我也不是很懂这个PBFT算法，我感觉我写的这个project都不一定是对的😂
